"""Added the ingredients to be nullable

Revision ID: 41bd821e672b
Revises: 9b9c13fe0939
Create Date: 2025-01-30 20:17:11.420211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41bd821e672b'
down_revision = '9b9c13fe0939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('ingredients',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('ingredients',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
